name: aas-gym pip install

on:
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch: {}
  pull_request:
    branches: [ "main" ]

jobs:
  install-check:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      contents: read
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet &
          sudo rm -rf /usr/local/lib/android &
          sudo rm -rf /opt/ghc &
          sudo rm -rf /opt/hostedtoolcache/CodeQL &
          sudo rm -rf /usr/local/share/boost &
          sudo rm -rf /usr/share/swift &
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" &
          wait
          sudo docker image prune --all --force
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Check disk space
        run: df -h

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Conda with Python 3.13
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: aas
          python-version: 3.13
          auto-activate-base: false
          use-only-tar-bz2: true 

      - name: Install aas-gym package
        run: |
          cd ./aas-gym/          
          pip install -e .

      - name: Check for dependency conflicts
        run: pip check

      - name: Verify Import
        run: python -c "import aas_gym; print('Successfully imported aas_gym')"
